### ISSUE TITLE
training

### ISSUE THREAD

**Issue by yy835055664** [Wadaboa/titanet#4]
Hello, thank you very much for providing such a good project, currently trying to reproduce your project.
Currently encountering a problem during the training phase. A file is missing because google.colab cannot be used. Could you please provide the W&B API key file? ,thank you very much!

**Comment by manhph2211** [comment]
You'd better create your own account on the official W&B website and then you will be provided a key that you want!

**Comment by Wadaboa** [comment]
Hi, as @manhph2211 said, I won't provide my own API key, please go ahead and create a W&B account (also remember to change `wandb.entity` in the `parameters.yml` file with your W&B username) or disable W&B altogether (in the `parameters.yml` file substitute `true` for `false` in the `wandb.enabled` key).
 
Closing this issue. Thanks,
Alessio.

**Comment by yy835055664** [comment]
Thanks a lot, I'll go ahead and reproduce your code next.



---Original---
From: ***@***.***&gt;
Date: Sun, May 1, 2022 11:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Wadaboa/titanet] training (Issue #4)




 
You'd better create your own account on the official W&amp;B website and then you will be provided a key that you want!
